plugins {
    id 'java'
}

group 'tugas'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'io.cucumber:cucumber-java:7.21.1'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.21.1'
    testImplementation 'org.junit.platform:junit-platform-suite:1.11.4'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.29.0'
    testImplementation 'io.github.bonigarcia:webdrivermanager:5.9.3'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named('test') {
    useJUnitPlatform()
    systemProperty("cucumber.junit-platform.naming-strategy", "long")
}
